### ISSUE TITLE
橙光还那菜鸡也配当业界毒瘤？

### ISSUE THREAD

**Issue by hokaso** [Uni-Gal/UniGal-Script#1]
游戏索引直接明文保存，分分钟就破掉了（此处@冰河）……之前花了两三天就爬完了橙光8w左右的游戏文本，有需要可以找我~以及下一步工作是通过VNR的特殊码破解pc端gal的文本，具体悬赏贴：https://hocassian.cn/archives/tech/8357/

**Comment by LaoshuBaby** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈好
