### ISSUE TITLE
[code.resource.sound] channel_id移动到 [code.action.soundcontrol]

### ISSUE THREAD

**Issue by Akarinnnnn** [Uni-Gal/UniGal-Script#4]
我觉得channel在定义声音的时候写死还是太早了，延后到播放的时候觉得好点

**Comment by LaoshuBaby** [comment]
按照之前QQ聊天中的机录，我们这个可能需要考虑您说的index等资产组织侧的工具完善后在进行这个
（先咕吧，先咕比较好，留待后面慢慢细解决

**Comment by LaoshuBaby** [comment]
反正春节期间大家咕一咕也没问题（给键盘放个假吧.JPG

（顺便，一直想怎么把QQ的私聊机录能够公开出来，真正做到开放，互动，IRC吗？（挠头

**Comment by Akarinnnnn** [comment]
这个先鸽着，清晰再说

**Comment by LaoshuBaby** [comment]
啊这个，忘记回复了，我是认为channel的id是属于channel这个对象的一部分，而control所操作的应该是一个sound对象，所以我觉得这两个是毫无关系的，这个挪动只是”看着更近了但是实际上打破了好不容易理顺清楚的抽象关系“，然后就忘记回复这回事了
（不过closed是好的，因为这个pr我必然rejected





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Uni-Gal/UniGal-Script] [code.resource.sound] channel_id移动到 [code.action.soundcontrol] (#4)





 
Closed #4.
 
&mdash;

**Comment by Akarinnnnn** [comment]
我认为channal不是对象。

**Comment by LaoshuBaby** [comment]
***，***
那可能是因为我oop中毒太严重了吧
<(_ _)&gt;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 中午12:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Uni-Gal/UniGal-Script] [code.resource.sound] channel_id移动到 [code.action.soundcontrol] (#4)




 
我认为channal不是对象。
